name: Terraform deploy to Azure
on:
  workflow_dispatch:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      # Push events on main branch
      - main
      - master



jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: 
      name: github.ref
    steps:
#    - name: "Checkout"
#      uses: actions/checkout@master

    - name: Echo Environment
      run: echo '${{ github.ref }} - ${{ secrets.SECRET }}'
